export { default as SectionTitle } from './SectionTitle/SectionTitle.vue'
export { default as SectionHighlight } from './SectionHighlight/SectionHighlight.vue'
export { default as SectionService } from './SectionService/SectionService.vue'
export { default as SectionPerson } from './SectionPerson/SectionPerson.vue'
export { default as SectionOffer } from './SectionOffer/SectionOffer.vue'
