export { default as HeaderPartial } from './HeaderPartial/HeaderPartial.vue'
export { default as FooterPartial } from './FooterPartial/FooterPartial.vue'
export { default as BrandPartial } from './BrandPartial/BrandPartial.vue'
export { default as OffersPartial } from './OffersPartial/OffersPartial.vue'
export { default as HighlightsPartial } from './HighlightsPartial/HighlightsPartial.vue'
export { default as ServicesPartial } from './ServicesPartial/ServicesPartial.vue'
export { default as MembersPartial } from './MembersPartial/MembersPartial.vue'
export { default as ContactsPartial } from './ContactsPartial/ContactsPartial.vue'
